language: python
matrix:
  include:
    - python: 2.7
    - python: 3.8
      dist: xenial
      sudo: true
# command to install dependencies
install:
  # set the version, normally done by gradle
  - echo 0.0.0 > VERSION.txt
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest tests