language: python
matrix:
  include:
    - python: 2.7
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest tests