language: python
python: 3.11-dev
dist: xenial
sudo: true
# command to install dependencies
install:
  # set the version, normally done by gradle
  - echo 0.0.0 > VERSION.txt
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest tests